fix #1100
mooltipass/moolticute pull request #1125
Opened 2023-01-20 00:07 UTC by rsrdesarrollo

fix #1100 

It adds a new config option checkbox and skips TLD validation when setting is enabled.

2023-01-20 12:18 UTC, bertvandepoel commented
I'm not very good at compiling Qt apps on my (relatively old) OS 😓 Would you mind including a screenshot? I'm hoping to help with the UX. While moolticute is very useable for IT people, it's proving to be really difficult for more regular users. I'm hoping to help improve that :)

2023-01-20 18:47 UTC, deXol requested changes
Hello,
Functionality looks good, but I built it and Settings page looks really strange:
![kép](https://user-images.githubusercontent.com/11043249/213779516-7d44b9a2-5bfc-4300-a3bc-8eafad5b443d.png)
Moolticute Settings text moved to the bottom, text is missing for the second setting.
Original UI:
![kép](https://user-images.githubusercontent.com/11043249/213780991-dab00335-6ba9-4853-8af3-8b5871458ca8.png)

2023-01-20 18:47 UTC, deXol commented on src/MainWindow.ui
> -    <height>632</height>
Can you revert this please? It is an automatically updated value, when you open the UI file it is updating it based on your Qt window size.

2023-01-20 18:47 UTC, deXol commented on src/MainWindow.ui
> +             <width>1014</width>
Same here as in line 10.

2023-01-20 18:47 UTC, deXol commented on src/MainWindow.ui
> +               <height>941</height>
Same here as in line 10.

2023-01-23 10:31 UTC, rsrdesarrollo commented
@deXol done!

2023-01-23 11:39 UTC, bertvandepoel commented
Does this PR exclusively add a setting, or does it also include some kind of warning or other indication when TLDs are listed that are not in the built-in list? I must admit I'm really not a fan of current behaviour where they are silently ignored (though I'm not sure that discussion is "in scope" for this PR)

2023-01-23 15:25 UTC, bertvandepoel commented
Awesome! :D Nevermind about what I said then!

2023-01-23 19:17 UTC, deXol commented
@rsrdesarrollo Window size constants are good now, but the Settings page is still off:
![kép](https://user-images.githubusercontent.com/11043249/214129195-0d8efd77-541d-4e22-9a1d-38faa66a7822.png)
Moolticute Settings text should be on the top and View daemon log should be a line above.

2023-01-27 17:26 UTC, rsrdesarrollo commented
@deXol now is really done.

2023-01-27 17:31 UTC, rsrdesarrollo commented
and now is really really done xD 

P.D: I hate qt-creator

2023-01-27 18:59 UTC, deXol approved these changes
nice, looks good now :)

2023-01-27 19:39 UTC, limpkin commented
thanks a lot @rsrdesarrollo !

2023-01-27 19:39 UTC, merged